# -*- coding: utf-8 -*-
from . import test_download_saveas_removed
from . import test_webhook_resource_security
from . import test_webhook_notification_security
from . import test_meli_login_no_token_exposure
from . import test_http_backend_contract
from . import test_no_global_price_precision
from . import test_crons_inactive_by_default
from . import test_product_template_list_price
from . import test_preserve_existing_meli_id
from . import test_posting_created_on_match
from . import test_explicit_meli_ids
from . import test_single_item_import
from . import test_sale_order_message_fields
from . import test_auth_http_status_detection
from . import test_unprocessable_item_response
from . import test_posting_update_error_response
from . import test_check_import_status_unset_fields
from . import test_image_download_timeout
from . import test_no_variants_log_noise
from . import test_no_token_secrets_in_logs
from . import test_token_expiry_metadata
from . import test_refresh_response_validation
from . import test_http_backend_selection
